version: '3.1'
services:
  stats-server:
    build: ./stats
    image: docker-image-application-stats:0.0.1
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    env_file: .stats-db-credentials.env
    environment:
      - SERVER_PORT=9090
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  stats-db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file: .stats-db-credentials.env

  ewm-service:
    build: ./ewm
    image: docker-image-application-ewm:0.0.1
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    env_file: .ewm-db-credentials.env
    environment:
      - SERVER_PORT=8080
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  ewm-db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file: .ewm-db-credentials.env
