create table if not exists endpoint_hit
(
    id         bigint generated by default as identity,
    app_id     varchar(255),
    created_on timestamp without time zone,
    entity_id  bigint,
    ip         varchar(255),
    uri        varchar(255),
    primary key (id)
);
